-- ==============================================================================
-- Andalusia Music Platform — Master Seed from Figma
-- Applies all canonical content directly to Supabase
-- ==============================================================================

-- 1. SITE SETTINGS (Singleton)
INSERT INTO public.site_settings (
  id,
  hero_headline,
  hero_subheadline,
  hero_image_url,
  hero_headline_en,
  hero_subheadline_en,
  about_headline,
  about_body,
  about_image_url,
  about_headline_en,
  about_body_en,
  booking_banner_title,
  booking_banner_body,
  booking_banner_title_en,
  booking_banner_body_en,
  artists_subtitle,
  artists_subtitle_en,
  events_subtitle,
  events_subtitle_en,
  academy_subtitle,
  academy_subtitle_en,
  booking_subtitle,
  booking_subtitle_en,
  contact_email,
  contact_phone,
  operational_regions,
  operational_regions_en,
  footer_mission,
  footer_mission_en,
  copyright_text,
  copyright_text_en,
  home_hero_primary_cta,
  home_hero_primary_cta_en,
  home_hero_secondary_cta,
  home_hero_secondary_cta_en,
  home_about_cta,
  home_about_cta_en,
  home_artists_heading,
  home_artists_heading_en,
  home_artists_cta,
  home_artists_cta_en,
  home_testimonials_heading,
  home_testimonials_heading_en,
  home_editorial_heading,
  home_editorial_heading_en,
  home_events_heading,
  home_events_heading_en,
  home_events_cta,
  home_events_cta_en,
  events_title,
  events_title_en,
  artists_title,
  artists_title_en,
  academy_title,
  academy_title_en,
  academy_kicker,
  academy_kicker_en,
  academy_tracks_heading,
  academy_tracks_heading_en,
  news_title,
  news_title_en,
  news_subtitle,
  news_subtitle_en,
  news_kicker,
  news_kicker_en,
  booking_title,
  booking_title_en
) VALUES (
  'default',
  'منصتك الأولى *لاكتشاف* ودعم *المواهب* الفنية والثقافية',
  'أندلسيا منصة متخصصة في تمثيل ودعم المواهب الإبداعية، وربط الفنانين بالأماكن والمناسبات التي تستحق الجمال.',
  '/assets/figma/hero-stage-landscape.png',
  'Your first place to *discover* and support artistic and cultural *talent*',
  'Andalusia represents and supports creative talent, connecting artists with the places and occasions that deserve beauty.',
  'نكتشف · نصل · نحتفي',
  'وُلدنا من إيمان عميق بأن الفن ليس ترفاً بل ضرورة. نعمل على تقريب المسافة بين الفنان الموهوب والجمهور الذي ينتظره، وبين المناسبة التي تستحق اللحظة الفنية التي تجعلها لا تُنسى. أندلسيا منصة متخصصة في تمثيل ودعم المواهب الإبداعية، وربط الفنانين بالأماكن والمناسبات التي تستحق الجمال.',
  '/assets/figma/about-musician.png',
  'We discover · We connect · We celebrate',
  'We were born from a deep belief that art is not a luxury but a necessity. We work to close the distance between a talented artist and the audience waiting for them, and between an occasion and the artistic moment that makes it unforgettable. Andalusia represents and supports creative talent, connecting artists with the places and occasions that deserve beauty.',
  'مناسبتك تستحق موسيقى حقيقية',
  'احجز فرقة أندلسيا لحفلتك، مطعمك، مهرجانك — واصنع لحظة لا تُنسى.',
  'Your occasion deserves real music',
  'Book Andalusia for your party, your restaurant, your festival — and make a moment no one forgets.',
  'كل فنان في أندلسيا يحمل قصة ومعاناة تحوّلت إلى موسيقى تلامس القلوب.',
  'Every artist at Andalusia carries a story, plays the soul of the East, and turns heritage into a sound for the future.',
  'مواعيد تترك أثراً جميلاً في قلوب عشاق الموسيقى الأصيلة.',
  'Dates that leave a beautiful mark on anyone who loves music with roots.',
  'برامج تعليمية موسيقية مع فنانين حقيقيين في بيئات صغيرة ومكثفة — تجربة تغير مسارك الفني.',
  'Educational music programs with real artists in small, intensive environments — an experience that will change your artistic path.',
  'احجز حفلتك الخاصة أو شاركنا فعاليتك القادمة.',
  'Book your private evening, or bring us into your next event.',
  'hello@andalusia.art',
  '+961 1 234 567',
  'لبنان · المغرب · الخليج',
  'Lebanon · Morocco · The Gulf',
  'مجموعة فنانين يؤمنون أن الإبداع هو الحياة والموسيقى هي الشعلة.',
  'A collective of artists who believe creativity is life and music is the spark.',
  '© أندلسيا ٢٠٢٥ — جميع الحقوق محفوظة',
  '© Andalusia 2025 — All rights reserved',
  'اكتشف الفنانين',
  'Discover the artists',
  'احجز الآن',
  'Book now',
  'تعرّف على فنانينا ←',
  'Meet our artists →',
  'أصوات تصنع التاريخ',
  'Voices that make history',
  'عرض جميع الفنانين ←',
  'View all artists →',
  'يقولون عن *أندلسيا*',
  'They say about *Andalusia*',
  'نكتب كي لا تضيع التفاصيل',
  'We write so the details are never lost',
  'نلتقي في المكان. في اللحظة',
  'We meet in the place. In the moment',
  'عرض كل الفعاليات',
  'View all events',
  'مواعيد تترك أثراً جميلاً.',
  'Dates that leave a beautiful mark.',
  'أصوات تصنع التاريخ',
  'Voices that make history',
  'تعلّم من اليد التي تعرف الطريق',
  'Learn from the hand that knows the way',
  'أكاديمية أندلسيا الموسيقية',
  'Andalusia Music Academy',
  'ثلاثة مسارات، موهبة واحدة',
  'Three tracks, one talent',
  'آخر الأخبار والمقالات',
  'Latest News and Articles',
  'اكتشف أحدث التغطيات الثقافية، الحوارات الفنية، وورش العمل التدريبية.',
  'Discover the latest cultural coverage, artistic dialogues, and workshops.',
  'الأرشيف الصحفي',
  'Press Archive',
  'مناسبتك تستحق موسيقى حقيقية. ♪',
  'Your occasion deserves real music. ♪'
)
ON CONFLICT (id) DO UPDATE SET
  hero_headline = EXCLUDED.hero_headline,
  hero_subheadline = EXCLUDED.hero_subheadline,
  hero_image_url = EXCLUDED.hero_image_url,
  hero_headline_en = EXCLUDED.hero_headline_en,
  hero_subheadline_en = EXCLUDED.hero_subheadline_en,
  about_headline = EXCLUDED.about_headline,
  about_body = EXCLUDED.about_body,
  about_image_url = EXCLUDED.about_image_url,
  about_headline_en = EXCLUDED.about_headline_en,
  about_body_en = EXCLUDED.about_body_en,
  booking_banner_title = EXCLUDED.booking_banner_title,
  booking_banner_body = EXCLUDED.booking_banner_body,
  booking_banner_title_en = EXCLUDED.booking_banner_title_en,
  booking_banner_body_en = EXCLUDED.booking_banner_body_en,
  artists_subtitle = EXCLUDED.artists_subtitle,
  artists_subtitle_en = EXCLUDED.artists_subtitle_en,
  events_subtitle = EXCLUDED.events_subtitle,
  events_subtitle_en = EXCLUDED.events_subtitle_en,
  academy_subtitle = EXCLUDED.academy_subtitle,
  academy_subtitle_en = EXCLUDED.academy_subtitle_en,
  booking_subtitle = EXCLUDED.booking_subtitle,
  booking_subtitle_en = EXCLUDED.booking_subtitle_en,
  contact_email = EXCLUDED.contact_email,
  contact_phone = EXCLUDED.contact_phone,
  operational_regions = EXCLUDED.operational_regions,
  operational_regions_en = EXCLUDED.operational_regions_en,
  footer_mission = EXCLUDED.footer_mission,
  footer_mission_en = EXCLUDED.footer_mission_en,
  copyright_text = EXCLUDED.copyright_text,
  copyright_text_en = EXCLUDED.copyright_text_en,
  home_hero_primary_cta = EXCLUDED.home_hero_primary_cta,
  home_hero_primary_cta_en = EXCLUDED.home_hero_primary_cta_en,
  home_hero_secondary_cta = EXCLUDED.home_hero_secondary_cta,
  home_hero_secondary_cta_en = EXCLUDED.home_hero_secondary_cta_en,
  home_about_cta = EXCLUDED.home_about_cta,
  home_about_cta_en = EXCLUDED.home_about_cta_en,
  home_artists_heading = EXCLUDED.home_artists_heading,
  home_artists_heading_en = EXCLUDED.home_artists_heading_en,
  home_artists_cta = EXCLUDED.home_artists_cta,
  home_artists_cta_en = EXCLUDED.home_artists_cta_en,
  home_testimonials_heading = EXCLUDED.home_testimonials_heading,
  home_testimonials_heading_en = EXCLUDED.home_testimonials_heading_en,
  home_editorial_heading = EXCLUDED.home_editorial_heading,
  home_editorial_heading_en = EXCLUDED.home_editorial_heading_en,
  home_events_heading = EXCLUDED.home_events_heading,
  home_events_heading_en = EXCLUDED.home_events_heading_en,
  home_events_cta = EXCLUDED.home_events_cta,
  home_events_cta_en = EXCLUDED.home_events_cta_en,
  events_title = EXCLUDED.events_title,
  events_title_en = EXCLUDED.events_title_en,
  artists_title = EXCLUDED.artists_title,
  artists_title_en = EXCLUDED.artists_title_en,
  academy_title = EXCLUDED.academy_title,
  academy_title_en = EXCLUDED.academy_title_en,
  academy_kicker = EXCLUDED.academy_kicker,
  academy_kicker_en = EXCLUDED.academy_kicker_en,
  academy_tracks_heading = EXCLUDED.academy_tracks_heading,
  academy_tracks_heading_en = EXCLUDED.academy_tracks_heading_en,
  news_title = EXCLUDED.news_title,
  news_title_en = EXCLUDED.news_title_en,
  news_subtitle = EXCLUDED.news_subtitle,
  news_subtitle_en = EXCLUDED.news_subtitle_en,
  news_kicker = EXCLUDED.news_kicker,
  news_kicker_en = EXCLUDED.news_kicker_en,
  booking_title = EXCLUDED.booking_title,
  booking_title_en = EXCLUDED.booking_title_en;

-- 2. ACADEMY COURSES
INSERT INTO public.academy_courses (
  id, title, title_en, track_category, track_category_en, description, description_en, display_order, is_published
) VALUES 
(
  'a1111111-1111-1111-1111-111111111111',
  'مدرسة العود',
  'Oud Academy',
  'مدرسة التراث',
  'Heritage Track',
  'دراسة أصول العود والمقامات الشرقية وتقنيات العزف الأندلسي مع نخبة من الأساتذة.',
  'Study the origins of the oud, oriental maqams, and Andalusian performance techniques with master artists.',
  1,
  true
),
(
  'a2222222-2222-2222-2222-222222222222',
  'فن الأداء والتخت الشرقي',
  'Ensemble & Performance',
  'التناغم الموسيقي',
  'Musical Harmony Track',
  'تدريب عملي على التفاعل الحي والارتجال داخل فرق التخت الشرقي الكلاسيكي.',
  'Hands-on training in live ensemble interaction and improvisation within traditional oriental takht groups.',
  2,
  true
),
(
  'a3333333-3333-3333-3333-333333333333',
  'الصوت والطرب الكلاسيكي',
  'Vocal & Classical Tarab',
  'الغناء والتنفس',
  'Vocal & Breathing Track',
  'تقنيات الصوت والموشحات الأندلسية والقصائد المغناة وتطوير المساحة الصوتية.',
  'Master vocal techniques, Andalusian muwashahat, sung poems, and vocal range expansion.',
  3,
  true
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  track_category = EXCLUDED.track_category,
  track_category_en = EXCLUDED.track_category_en,
  description = EXCLUDED.description,
  description_en = EXCLUDED.description_en,
  display_order = EXCLUDED.display_order,
  is_published = EXCLUDED.is_published;

-- 3. FEATURED ARTIST (Sara Alsawt)
INSERT INTO public.artists (
  id, slug, name, name_en, genre_tag, genre_tag_en, city, city_en, quote, quote_en, short_bio, short_bio_en, is_published, is_featured, display_order
) VALUES (
  'b1111111-1111-1111-1111-111111111111',
  'sara-alsawt',
  'سارة الصوت',
  'Sara Alsawt',
  'غناء أصيل وموشحات أندلسية',
  'Classical Tarab & Andalusian Vocals',
  'بيروت — لبنان',
  'Beirut — Lebanon',
  'الصوت هو المرآة الأصدق للروح — لا تكذب على جمهورك أبداً.',
  'The voice is the truest mirror of the soul — never lie to your audience.',
  'مغنية متخصصة في الطرب الأصيل والغناء العاطفي. صوتها يحمل دفء الأرض وعمق التراث مع لمسة معاصرة تلامس الأجيال.',
  'A singer specializing in authentic tarab and emotive vocals. Her voice carries the warmth of the earth and the depth of heritage with a contemporary touch.',
  true,
  true,
  1
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  genre_tag = EXCLUDED.genre_tag,
  genre_tag_en = EXCLUDED.genre_tag_en,
  city = EXCLUDED.city,
  city_en = EXCLUDED.city_en,
  quote = EXCLUDED.quote,
  quote_en = EXCLUDED.quote_en,
  short_bio = EXCLUDED.short_bio,
  short_bio_en = EXCLUDED.short_bio_en,
  is_published = EXCLUDED.is_published,
  is_featured = EXCLUDED.is_featured,
  display_order = EXCLUDED.display_order;
